[package]
name = "kaubo-vfs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Virtual File System abstraction for Kaubo"

[features]
default = ["std"]
std = []

[dependencies]
